 CREATE TABLE USUARIO (
        DATA_NASCIMENTO DATE,
        DATA_ATUALIZACAO TIMESTAMP(6),
        DATA_CRIACAO TIMESTAMP(6),
        UUID UUID NOT NULL,
        NOME VARCHAR(255),
        PRIMARY KEY (UUID)
    )